; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform_packages=
  framework-industrialshields-esp32@https://apps.industrialshields.com/main/arduino/boards/industrialshields-boards-esp32-2.3.1.tar.bz2
lib_deps =
    https://github.com/Industrial-Shields/arduino-Modbus.git
    dvarrel/ESPping@^1.0.5
lib_ignore = QNEthernet

[env:board]
platform = https://github.com/Industrial-Shields/platform-industrialshields-esp32.git
; board = esp32plc_21 / 14iosplc_ma
board = 14iosplc_ma
custom_version = 3 ; or 1
custom_click1 = None ; or GPRS
custom_click2 = None ; or GPRS
framework = arduino
monitor_speed = 115200
